### ISSUE TITLE
为什么不给我塔跌引流？

### ISSUE THREAD

**Issue by hikariyo** [FurryR/helang2#1]
恨来自不知道哪

**Comment by hikariyo** [comment]
哦，看错了

**Comment by FurryR** [comment]
我去，什么HeAssembly战线

**Comment by hikariyo** [comment]
为什么Reopen，是不是要给我挂到耻辱柱
恨来自 **Cyber Spaces**

**Comment by FurryR** [comment]
> 为什么Reopen，是不是要给我挂到耻辱柱 恨来自 **Cyber Spaces**

正确的，就是要狠狠地鞭打你🥵🥵🥵

**Comment by hikariyo** [comment]
你怎么不给我挂到我的README里面？我给你加上吧

**Comment by FurryR** [comment]
正确的捏，这下close了

**Comment by hikariyo** [comment]
但是你要改名 HeAssembly 😠

**Comment by FurryR** [comment]
好好好
